### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by belgishboy** [belgishboy/minishell#50]
@belgishboy check freeing issues (probably incorrect ifs)
@belgishboy append
@belgishboy  heredoc
@c8p2d01 check parent/child fix
@hennneh fixing cd
@ALL check for leaks and fd leaks
@LePlaYa try to break the code

**Comment by belgishboy** [comment]
done freeing issues

**Comment by hennneh** [comment]
err_num is initialized twice

**Comment by belgishboy** [comment]
Done append

**Comment by belgishboy** [comment]
heredoc returns (0), we could decide to print that we just didnt do it
