### ISSUE TITLE
invalid read in pipesplit

### ISSUE THREAD

**Issue by c8p2d01** [belgishboy/minishell#92]
Invalid read of size 1
==15357==    at 0x100005515: pipe_split (in ./minishell)
==15357==    by 0x100005C60: extract_cmd (in ./minishell)
==15357==    by 0x100002ECF: shell (in ./minishell)
==15357==    by 0x100002F79: main (in ./minishell)
==15357==  Address 0x100900e73 is 0 bytes after a block of size 3 alloc'd
==15357==    at 0x100127545: malloc (in /usr/local/Cellar/valgrind/HEAD-6ff08b6/libexec/valgrind/vgpreload_memcheck-amd64-darwin.so)
==15357==    by 0x10015ACDC: xmalloc (in /goinfre/cdahlhof/.brew/Cellar/readline/8.1.2/lib/libreadline.8.1.dylib)
==15357==    by 0x100138D29: readline_internal_teardown (in /goinfre/cdahlhof/.brew/Cellar/readline/8.1.2/lib/libreadline.8.1.dylib)
==15357==    by 0x100138858: readline (in /goinfre/cdahlhof/.brew/Cellar/readline/8.1.2/lib/libreadline.8.1.dylib)
==15357==    by 0x100002E86: shell (in ./minishell)
==15357==    by 0x100002F79: main (in ./minishell)

**Comment by belgishboy** [comment]
not that ----Dont know if readline automatically puts a '\0' but dont think that is the issue------
